version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      # Android the primary container
      - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Change Permissions
          command: sudo chmod +x gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Setup and Start emulator
          command: |
            android list targets
            android create avd -n emulatorwithgoogleapi22 -t 12 --tag google_apis
            echo 'vm.heapSize=512' >> ~/.android/avd/emulatorwithgoogleapi22.ini
            echo 'hw.ramSize=1024' >> ~/.android/avd/emulatorwithgoogleapi22.ini
            cat ~/.android/avd/emulatorwithgoogleapi22.ini
            emulator -avd emulatorwithgoogleapi22 -no-audio -no-window :
              background: true
              parallel: true
            circle-android wait-for-boot
            adb shell input keyevent 82
            adb shell svc power stayon true
            adb shell settings put global window_animation_scale 0
            adb shell settings put global transition_animation_scale 0
            adb shell settings put global animator_duration_scale 0
      - run:
          name: Run EspressoTests
          command: ./gradlew connectedAndroidTest
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/reports