version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      # Android the primary container
      - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - setup_remote_docker:   # (2)
              docker_layer_caching: true # (3)
      - run:
          name: Pre Docker cleanup
          command: docker volume prune --force
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Change Permissions
          command: sudo chmod +x gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Assemble APKs
          command: ./gradlew assembleAndroidTest assemble
      - run:
          name: Dump Google Cloud Credentials to file
          command: echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
      - run: gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
      - run: gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      - run:
          name: Create directory to store test results
          command: mkdir firebase
      #- run:
      #    name: Run Espresso UI Tests in Firebase Test Lab
      #    command: gcloud firebase test android run --type instrumentation --app app/build/outputs/apk/debug/app-debug.apk --test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk --device model=Nexus6P,version=27,locale=en,orientation=portrait --environment-variables coverage=true,coverageFile=/sdcard/coverage.ec --directories-to-pull=/sdcard --timeout 30m
      #    no_output_timeout: 30m
      - run:
          name: Download instrumented test results from Firebase Test Lab
          command: gsutil -d -m cp -r -U -e "`gsutil ls gs://test-lab-qbdm2npcvh60u-i046mbwutkrw2 | tail -1`*" firebase/ 2> /dev/null || true
      - store_artifacts:
          path: firebase/
          destination: reports
      - store_test_results:
          path: firebase/Nexus6P-27-en-portrait
      - run:
          name: Move Firebase coverage report
          command: mkdir -p app/build/outputs/code-coverage/connected && cp firebase/Nexus6P-27-en-portrait/artifacts/coverage.ec app/build/outputs/code-coverage/connected/coverage.ec
      - run:
          name: Generate JaCoCo report
          command: ./gradlew -PciBuild=true :app:jacocoTestReport
      - store_artifacts:
          path: app\build\reports\jacoco\jacocoTestReport
          destination: reports